### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jontebol** [jontebol/planitors#1]
Lägger upp lite grejer som ska göras:

- [ ] Lägga in vettig duration på missions
- [x] Klickbara rader
- [x] Level i mission-formuläret
- [ ] Notifikationer
- [ ] Pengar i form av co2-pris?
- [ ] Någon mekanism för att inte komma åt framtida levels och hur/när man klarar en level
